command:
  - streamlit
  - run
  - app.py
  - "--server.address"
  - "0.0.0.0"
  - "--server.port"
  - "$DATABRICKS_APP_PORT"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: "b3ba19df33b9f4c0"
